import type { Metadata } from "next";
import "../globals.css";
import { AppSidebar } from "@/components/ui/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={"w-full flex"}>
      <AppSidebar />
      {children}
    </div>
  );
}
